### ISSUE TITLE
Support adding contents in the form of blobs

### ISSUE THREAD

**Issue by diptanu** [diptanu/indexify#109]
Indexify needs to have a mechanism to upload blobs such as PDFs, images and video files, or refer to a link to a blob store where they are stored. 

The API on the server for uploading blobs - 
```
POST
/repositories/{reposistory}/files
```

.. and when the blob is already on a blob store and Indexify can read from there - 
```
POST
/repositories/{repository}/remote_files
```

The config of the server should accept a blob storage backend -
```
pub struct S3Config {
   region: String,
   bucket: String,
}
pub struct BlobStorageBackend {
  s3_backend: Option<S3Config>,
  file_system: Option<FSConfig>,
}
```

Under the hood we can create a table to track both files which are uploaded directly to indexify or the ones we are going to download from remote storage services.

The executors should be passed along the URLs of the blobs for extraction. The executor will download them directly, and feed them into the extractors.

**Comment by yenicelik** [comment]
Was this implemented with this commit, or is there more missing? https://github.com/diptanu/indexify/commit/f850518cd253d4ef507b626e8902f65ba576c514

**Comment by diptanu** [comment]
This is done!
