### ISSUE TITLE
Publish Indexify binaries for download

### ISSUE THREAD

**Issue by diptanu** [diptanu/indexify#215]
Indexify binaries needs to be published as releases and made available for download. Write a Github workflow that we can trigger to manually build the binaries for now, and in the future we can trigger them when we tag the main branch for new releases.

We need binaries for - 
1. Linux 
2. Windows
3. Mac (M series only)

**Comment by rakshith-ravi** [comment]
This can be closed @diptanu

**Comment by rakshith-ravi** [comment]
For searchability purposes, this was fixed in #225
